### ISSUE TITLE
Install python38 from scl repository

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/role_python#3]
1. Install python38 from scl repository, and set environment.
2. set soft link */opt/rh/rh-python38/root/usr/lib/python3.8*  to */usr/lib/python3.8*

**Comment by qiaofeng1227** [comment]
AmazonLinux2 install error

**Comment by tqf6** [comment]
```
TASK [role_python : Install python3] *******************************************
fatal: [35.153.79.3]: FAILED! => {"changed": false, "msg": "No package matching 'rh-python38' found available, installed or updated", "rc": 126, "results": ["No package matching 'rh-python38' found available, installed or updated"]}
```

**Comment by tqf6** [comment]
35.153.79.3
python on AmazonLinux2

**Comment by zengxc-1996** [comment]
tested on aliyun ubuntu 20:
```
TASK [role_mysql : Install Depend on the package] ***************************************************************************************************************************
fatal: [47.243.150.168]: FAILED! => {"changed": false, "cmd": "apt-get update", "msg": "Traceback (most recent call last):\n  File \"/usr/lib/cnf-update-db\", line 8, in <module>\n    from CommandNotFound.db.creator import DbCreator\n  File \"/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py\", line 11, in <module>\n    import apt_pkg\nModuleNotFoundError: No module named 'apt_pkg'\nE: Problem executing scripts APT::Update::Post-Invoke-Success 'if /usr/bin/test -w /var/lib/command-not-found/ -a -e /usr/lib/cnf-update-db; then /usr/lib/cnf-update-db > /dev/null; fi'\nE: Sub-process returned an error code", "rc": 100, "stderr": "Traceback (most recent call last):\n  File \"/usr/lib/cnf-update-db\", line 8, in <module>\n    from CommandNotFound.db.creator import DbCreator\n  File \"/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py\", line 11, in <module>\n    import apt_pkg\nModuleNotFoundError: No module named 'apt_pkg'\nE: Problem executing scripts APT::Update::Post-Invoke-Success 'if /usr/bin/test -w /var/lib/command-not-found/ -a -e /usr/lib/cnf-update-db; then /usr/lib/cnf-update-db > /dev/null; fi'\nE: Sub-process returned an error code\n", "stderr_lines": ["Traceback (most recent call last):", "  File \"/usr/lib/cnf-update-db\", line 8, in <module>", "    from CommandNotFound.db.creator import DbCreator", "  File \"/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py\", line 11, in <module>", "    import apt_pkg", "ModuleNotFoundError: No module named 'apt_pkg'", "E: Problem executing scripts APT::Update::Post-Invoke-Success 'if /usr/bin/test -w /var/lib/command-not-found/ -a -e /usr/lib/cnf-update-db; then /usr/lib/cnf-update-db > /dev/null; fi'", "E: Sub-process returned an error code"], "stdout": "Hit:1 http://mirrors.cloud.aliyuncs.com/ubuntu focal InRelease\nGet:2 http://mirrors.cloud.aliyuncs.com/ubuntu focal-updates InRelease [114 kB]\nGet:3 http://mirrors.cloud.aliyuncs.com/ubuntu focal-security InRelease [114 kB]\nHit:4 http://nginx.org/packages/ubuntu focal InRelease\nFetched 228 kB in 1s (452 kB/s)\nReading package lists...\n", "stdout_lines": ["Hit:1 http://mirrors.cloud.aliyuncs.com/ubuntu focal InRelease", "Get:2 http://mirrors.cloud.aliyuncs.com/ubuntu focal-updates InRelease [114 kB]", "Get:3 http://mirrors.cloud.aliyuncs.com/ubuntu focal-security InRelease [114 kB]", "Hit:4 http://nginx.org/packages/ubuntu focal InRelease", "Fetched 228 kB in 1s (452 kB/s)", "Reading package lists..."]}

```
[apt_pkg](https://github.com/ansible/ansible/issues/14468)

tested on aliyun centos 7:
```
TASK [role_mysql : Install MySQL Client] ************************************************************************************************************************************
fatal: [8.210.16.248]: FAILED! => {"changed": false, "msg": "The Python 2 bindings for rpm are needed for this module. If you require Python 3 support use the `dnf` Ansible module instead.. The Python 2 yum module is needed for this module. If you require Python 3 support use the `dnf` Ansible module instead."}

```

**Comment by zengxc-1996** [comment]
OS default version is 3.8, now I install python3.9

```
root@iZj6c47yf0hxjfwsw3akjsZ:~# python3.8
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import apt
>>> import apt_pkg

>>> 
root@iZj6c47yf0hxjfwsw3akjsZ:~# python3.9
Python 3.9.5 (default, May 19 2021, 11:32:47) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import apt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'
>>> 
```
python3.9 no module apt.

ansible apt moudule can't  use.
